// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package ft

import (
	"context"
	"log"

	"cloud.google.com/go/firestore"
)

func CreateUser(ctx context.Context, client *firestore.Client, data Dict) (*firestore.DocumentRef, error) {
	df, _, err := client.Collection("somethings").Add(ctx, data)
	log.Println(df.ID)
	if err != nil {
		log.Fatalf("Failed adding alovelace: %v", err)
		return &firestore.DocumentRef{}, err
	}
	return df, nil
}

func GetUser(ctx context.Context, client *firestore.Client, docID string) (*User, error) {
	dsnap, err := client.Collection("somethings").Doc(docID).Get(ctx)
	if err != nil {
		return nil, err
	}
	var something User
	dsnap.DataTo(&something)
	log.Println("Document data: %#v\n", something)
	return &something, nil
}

func GetUserAsDict(ctx context.Context, client *firestore.Client, docID string) (Dict, error) {
	dsnap, err := client.Collection("somethings").Doc(docID).Get(ctx)
	if err != nil {
		return nil, err
	}

	m := dsnap.Data()
	log.Println("Document data: %#v\n", m)
	return m, nil
}

func CreateArticle(ctx context.Context, client *firestore.Client, data Dict) (*firestore.DocumentRef, error) {
	df, _, err := client.Collection("somethings").Add(ctx, data)
	log.Println(df.ID)
	if err != nil {
		log.Fatalf("Failed adding alovelace: %v", err)
		return &firestore.DocumentRef{}, err
	}
	return df, nil
}

func GetArticle(ctx context.Context, client *firestore.Client, docID string) (*Article, error) {
	dsnap, err := client.Collection("somethings").Doc(docID).Get(ctx)
	if err != nil {
		return nil, err
	}
	var something Article
	dsnap.DataTo(&something)
	log.Println("Document data: %#v\n", something)
	return &something, nil
}

func GetArticleAsDict(ctx context.Context, client *firestore.Client, docID string) (Dict, error) {
	dsnap, err := client.Collection("somethings").Doc(docID).Get(ctx)
	if err != nil {
		return nil, err
	}

	m := dsnap.Data()
	log.Println("Document data: %#v\n", m)
	return m, nil
}
